# Generated by Django 5.1.7 on 2025-03-24 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamesession',
            name='status',
            field=models.CharField(choices=[('p', 'pre-started'), ('s', 'started'), ('f', 'finished')], default='p', max_length=1),
        ),
    ]
