# Generated by Django 5.1.7 on 2025-03-24 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_alter_gamesession_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamesession',
            name='current_round',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
