# Generated by Django 5.1.7 on 2025-03-24 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_alter_gamesession_current_round'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameround',
            name='done_by_user1',
        ),
        migrations.RemoveField(
            model_name='gameround',
            name='done_by_user2',
        ),
        migrations.AddField(
            model_name='gameround',
            name='user1_answered_questions',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gameround',
            name='user2_answered_questions',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
